name: Native compilation

on:
  workflow_dispatch:

jobs:
  compile-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - run: sudo apt-get install default-jre
     
      - name: "Install CMake"
        uses: Symbitic/install-cmake@v0.1.0
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - run: pwd
      - run: ls
      - run: cd ..
      - run: pwd
      - run: ls
      
      - run: cd native
      - run: pwd
      - run: cmake --build ./ --clean-first 
      
      - uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: ./lib
        
        
      

      
