name: Native compilation

on:
  workflow_dispatch:

jobs:
  compile-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: "Install Mesa"
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install mesa-common-dev:amd64 mesa-common-dev:i386
          
      - name: "Install JDK"
        run: sudo apt-get install default-jre
        
      - name: "Install GCC multilib"
        run: sudo apt-get install gcc-multilib g++-multilib
          
      - name: "Compile"
        run: |
          cd native
          cmake .
          cmake --build ./ 
      
      - name: "Upload libraries"
        uses: actions/upload-artifact@v2
        with:
          name: Linux
          path: ./native/lib
          
  compile-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Compile"
        run: |
          cd native
          cmake .
          cmake -DCMAKE_GENERATOR_PLATFORM=x64 --build ./
          cmake -DCMAKE_GENERATOR_PLATFORM=Win32 --build ./
          
      - name: "Upload libraries"
        uses: actions/upload-artifact@v2
        with:
          name: Windows 2
          path: ./native/Debug
        
      

      
