name: Native compilation

on:
  workflow_dispatch:

jobs:
  compile-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - run: sudo apt-get install default-jre
     
      - name: "CMake build"
        uses: ashutoshvarma/action-cmake-build@v1
        with:
          build-dir: ${{runner.workspace}}/natives
          build-type: MinSizeRel
      

      
