name: Test platforms

on:
  workflow_dispatch:

jobs:
  test:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - run: |
        mkdir output
        cd output
        chmod +x ../gradlew
        ../gradlew test
        
    - name: "Upload outputs"
      uses: actions/upload-artifact@v2
      with:
        name: Linux
        path: ./output
