name: Test platforms

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: "Preparing OpenGL"
      uses: openrndr/setup-opengl@v1.1
    
    - name: "Testing"
      run: |
        chmod +x ./gradlew
        xvfb-run ./gradlew test
        
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: "Testing"
      run: |
        chmod +x ./gradlew
        ./gradlew test
      
