name: Test platforms

on:
  pull_request:
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: openrndr/setup-opengl@v1.1
    
    - name: "Testing"
      run: |
        chmod +x ./gradlew
        xvfb-run ./gradlew test
