name: Test platforms

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: "Preparing OpenGL"
      uses: openrndr/setup-opengl@v1.1
    
    - name: "Testing"
      run: |
        chmod +x ./gradlew
        xvfb-run ./gradlew test
        
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: "Testing"
      run: |
        chmod +x ./gradlew
        ./gradlew test
        
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: "Preparing OpenGL"
      shell: cmd
      run: |
        curl.exe -L --output mesa.7z --url https://github.com/pal1000/mesa-dist-win/releases/download/20.3.2/mesa3d-20.3.2-release-msvc.7z
        "C:\Program Files\7-Zip\7z.exe" x mesa.7z
        copy x64\libgallium_wgl.dll ./
        copy x64\opengl32.dll ./
        copy x64\libglapi.dll ./
        
    - name: "Testing"
      run: ./gradlew test
