name: Test platforms

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: "Testing"
      continue-on-error: true
      run: |
        chmod +x ./gradlew
        ./gradlew test
        
    - name: "Upload outputs"
      uses: actions/upload-artifact@v2
      with:
        name: Linux
        path: ./
