name: Test platforms

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: "Preparing OpenGL"
      run: |
        sudo add-apt-repository ppa:kisak/kisak-mesa
        sudo apt update
        sudo apt install mesa-utils
    
    - name: "Testing"
      run: |
        chmod +x ./gradlew
        xvfb-run ./gradlew test
        
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: "Testing"
      run: |
        chmod +x ./gradlew
        ./gradlew test

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1

    - name: "Preparing OpenGL"
      shell: pwsh
      run: |
        wget "https://github.com/pal1000/mesa-dist-win/releases/download/23.1.6/mesa3d-23.1.6-release-mingw.7z" -outfile "mesa3d.7z"
        7z e 'mesa3d.7z'
        
    
    - name: "Testing"
      run: |
        ./gradlew.bat test
      
